import type { Metadata } from "next";
import { Noto_Serif_Bengali} from "next/font/google";
import "./globals.css";
import HeaderPage from "./component/Header";
import NavLinksPage from "./component/NavLinks";
import Footer from "./component/Footer";
import { ToastContainer } from "react-toastify";
import { Suspense } from "react";


const  NotoSerifBengali  =  Noto_Serif_Bengali ({
  
  subsets: ["latin","bengali"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${NotoSerifBengali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-sky-50">
        
        <div className="bg-white"><HeaderPage/>
        <Suspense fallback={<div className="h-16"></div>}>
          <NavLinksPage/>
        </Suspense>
        
        </div>
        {children}
        <ToastContainer />
        <Footer></Footer>
        </body>
    </html>
  );
}